"""PreToolUse gate for Write/Edit/MultiEdit/NotebookEdit.

Blocks:
  - any edit under data/ (raw snapshots are immutable; curated is generated by `itrade ingest`)
  - edits to config/project.toml (only the owner advances the phase, after /gate-check)
  - secret files and hard-coded credentials
  - broker / order-placement code in Python (always)
  - IBKR API code in C# outside src/ITrade.Broker.IBKR/ and spikes/ibkr-feasibility/
  - live IB Gateway ports before the live pilot (phase 8)
"""

from __future__ import annotations

from _common import (
    BROKER_CODE,
    CSHARP_BROKER_CODE,
    CSHARP_BROKER_DIRS,
    LIVE_PORT,
    SECRET_ASSIGNMENT,
    current_phase,
    deny,
    new_content,
    project_dir,
    read_input,
    rel_path,
)

SECRET_SUFFIXES = (".pem", ".key", ".p12", ".pfx")


def main() -> None:
    payload = read_input()
    tool_input = payload.get("tool_input", {}) or {}
    file_path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    root = project_dir(payload)
    rel = rel_path(file_path, root) if file_path else None
    if rel is None:
        return

    if rel.startswith("data/raw/"):
        deny("data/raw/ holds immutable vendor snapshots. Never edit them; re-run `uv run itrade ingest`.")
    if rel.startswith("data/"):
        deny("data/ is generated. Change the pipeline in src/itrade/data/ and re-run `uv run itrade ingest`.")
    if rel == "config/project.toml":
        deny(
            "config/project.toml sets the project phase. Only the owner edits it, after "
            "`/gate-check` passes. Tell the user what gate evidence is still missing instead."
        )
    name = rel.rsplit("/", 1)[-1]
    if name.startswith(".env") or name.endswith(SECRET_SUFFIXES) or rel.startswith("secrets/"):
        deny("Secret files are off-limits. Credentials live in environment variables / the OS keychain.")
    if rel.startswith(".claude/"):
        return  # hook/agent definitions legitimately mention the patterns below

    text = new_content(tool_input)
    if SECRET_ASSIGNMENT.search(text):
        deny("This looks like a hard-coded credential. Read it from an environment variable instead.")

    if rel.endswith(".py") and BROKER_CODE.search(text):
        deny(
            "Python never talks to the broker (docs/PLAN.md §2.5). Orders are sent only by the C# "
            "ExecutionService through ITrade.Broker.IBKR."
        )

    if rel.endswith(".cs") and CSHARP_BROKER_CODE.search(text):
        if not rel.startswith(CSHARP_BROKER_DIRS):
            deny(
                "IBKR API code is allowed only in src/ITrade.Broker.IBKR/ and "
                "spikes/ibkr-feasibility/ (docs/PLAN.md §3.2). Other code uses IBrokerGateway."
            )
        if current_phase(root) < 8 and LIVE_PORT.search(text):
            deny("Live IB Gateway ports (4001/7496) are blocked until the live pilot (phase 8).")


if __name__ == "__main__":
    main()
