<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>9e176ec1-7c00-479f-8f14-66356838e083</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ITrade.Domain\ITrade.Domain.csproj" />
    <ProjectReference Include="..\ITrade.Application\ITrade.Application.csproj" />
    <ProjectReference Include="..\ITrade.Infrastructure\ITrade.Infrastructure.csproj" />
    <ProjectReference Include="..\ITrade.Broker.IBKR\ITrade.Broker.IBKR.csproj" />
  </ItemGroup>

</Project>
